// GENERATED by scripts/gen_viz_types.py — do not edit.
// Row types + status unions, single-sourced from src/sssf/db_schema.py.
// shared/types.ts re-exports these under the UI-facing names.
// Drift fails CI (tests/test_gen_viz_types.py regenerates and diffs).

/** sessions.status — a run is running until it earns success. */
export type SessionStatus = 'running' | 'success' | 'fail';

/** phases.status — queued only for manifest-declared phases not yet entered. */
export type PhaseStatus = 'queued' | 'running' | 'success' | 'fail' | 'not_passed';

/** phases.kind — decides which lane a block renders in. */
export type PhaseKind = 'engineer' | 'code' | 'agent';

/** events.type — every type the engine emits (the viz union was missing `integration`; this generated union fixed it). */
export type EventType = 'phase_start' | 'phase_end' | 'agent_start' | 'agent_end' | 'tool_call' | 'handoff' | 'gate_pass' | 'gate_fail' | 'log' | 'error' | 'integration';

/** `sessions` table — generated from db_schema.SessionsRow. */
export interface SessionsRow {
  adw_id: string;
  /** ADW script(s) that ran this session, e.g. "adw_plan + adw_build_test". */
  adw_name: string | null;
  request: string | null;
  status: SessionStatus | null;
  engineer: string | null;
  started_at: string | null;
  ended_at: string | null;
  total_tokens: number;
  total_cost: number;
  /** 1 once archived out of the review list. Review state, not run state. Null on dbs predating the column. */
  archived: number | null;
}

/** `phases` table — generated from db_schema.PhasesRow. */
export interface PhasesRow {
  phase_id: string;
  adw_id: string;
  seq: number | null;
  name: string | null;
  kind: PhaseKind | null;
  owner: string | null;
  description: string | null;
  status: PhaseStatus;
  attempt: number;
  retries: number;
  error: string | null;
  started_at: string | null;
  ended_at: string | null;
}

/** `events` table — generated from db_schema.EventsRow. */
export interface EventsRow {
  /** SQLite rowid — the stable ordering key the reader selects. */
  rowid: number;
  event_id: string;
  adw_id: string | null;
  phase_id: string | null;
  parent_id: string | null;
  type: EventType | null;
  name: string | null;
  payload_json: string | null;
  tokens: number | null;
  started_at: string | null;
  ended_at: string | null;
}

/** `envelopes` table — generated from db_schema.EnvelopesRow. */
export interface EnvelopesRow {
  envelope_id: string;
  adw_id: string | null;
  phase_id: string | null;
  agent: string | null;
  /** Name of the data_types model the response was parsed against. */
  output_type: string | null;
  payload_json: string | null;
  /** SQLite integer boolean. */
  valid: number | null;
  attempt: number | null;
  created_at: string | null;
}

/** `gate_results` table — generated from db_schema.GateResultsRow. */
export interface GateResultsRow {
  id: number;
  adw_id: string | null;
  phase_id: string | null;
  attempt: number | null;
  gate: string | null;
  /** SQLite integer boolean. */
  passed: number | null;
  violations_json: string | null;
  /** JSON array of GateCheck — the per-item evidence behind the verdict. Null on dbs predating the column. */
  checks_json: string | null;
  created_at: string | null;
}

/** `processes` table — generated from db_schema.ProcessesRow. */
export interface ProcessesRow {
  id: number;
  adw_id: string | null;
  kind: string | null;
  name: string | null;
  pid: number | null;
  command: string | null;
  started_at: string | null;
  ended_at: string | null;
}

/** `agent_sessions` table — generated from db_schema.AgentSessionsRow. */
export interface AgentSessionsRow {
  adw_id: string;
  agent: string;
  coding_agent: string | null;
  model: string | null;
  /** The agent's lane color from sssf.config.yaml, e.g. "#a78bfa". Null on dbs predating the column. */
  color: string | null;
  session_id: string | null;
  /** Window occupancy after the agent's last turn. Null on dbs predating the column. */
  context_tokens: number | null;
  /** The model's context ceiling; 0/NULL = unknown. Null on dbs predating the column. */
  context_window: number | null;
  created_at: string | null;
  last_used_at: string | null;
}

/** `tickets` table — generated from db_schema.TicketsRow. */
export interface TicketsRow {
  id: string;
  provider: string;
  external_id: string | null;
  title: string;
  description: string | null;
  status: string;
  prompt_file: string | null;
  adw_id: string | null;
  source_url: string | null;
  context: string;
  /** idea | implementation. */
  kind: string;
  /** Permanent origin-of-creation flag: plan-created tickets are tracked; synced tickets are not. */
  tracked: number;
  /** internal | jira | gitlab | github. */
  origin: string;
  parent_id: string | null;
  spec: string;
  rejection_feedback: string;
  created_at: string | null;
  updated_at: string | null;
}

/** `ticket_events` table — generated from db_schema.TicketEventsRow. */
export interface TicketEventsRow {
  id: number;
  ticket_id: string;
  event_type: string;
  actor: string;
  payload: string;
  created_at: string;
}

/** `ticket_runs` table — generated from db_schema.TicketRunsRow. */
export interface TicketRunsRow {
  ticket_id: string;
  adw_id: string;
  created_at: string | null;
}

/** `ticket_mrs` table — generated from db_schema.TicketMrsRow. */
export interface TicketMrsRow {
  ticket_id: string;
  repo: string;
  iid: string;
  url: string;
  created_at: string | null;
}

/** `notify_threads` table — generated from db_schema.NotifyThreadsRow. */
export interface NotifyThreadsRow {
  ticket_id: string;
  channel: string;
  thread_ts: string;
  updated_at: string | null;
}

/** `notify_events` table — generated from db_schema.NotifyEventsRow. */
export interface NotifyEventsRow {
  id: number;
  ticket_id: string;
  ts: string;
  ok: number;
  error: string | null;
  attempts: number;
  thread_ts: string | null;
  channel: string | null;
}

/** `sandbox_run` table — generated from db_schema.SandboxRunRow. */
export interface SandboxRunRow {
  adw_id: string;
  container: string;
  container_port: number | null;
  host_port: number | null;
  review_url: string | null;
  review_command: string | null;
  instructions: string;
  /** 'up' | 'stopped'. */
  status: string | null;
  updated_at: string | null;
}

/** `workbench_runs` table — generated from db_schema.WorkbenchRunsRow. */
export interface WorkbenchRunsRow {
  adw_id: string;
  container: string;
  worktree: string;
  container_port: number | null;
  host_port: number | null;
  url: string | null;
  status: string | null;
  created_at: string | null;
  updated_at: string | null;
}
