-- GENERATED by scripts/gen_viz_types.py — do not edit.
-- Derived snapshot of the schema contract (src/sssf/db_schema.py).
-- The pydantic models are authoritative; this file is for humans and
-- DB tools. Additive changes land in db_schema.MIGRATIONS, not here.

CREATE TABLE IF NOT EXISTS sessions (
  adw_id TEXT PRIMARY KEY,
  adw_name TEXT,
  request TEXT,
  status TEXT,
  engineer TEXT,
  started_at TEXT,
  ended_at TEXT,
  total_tokens INTEGER DEFAULT 0,
  total_cost REAL DEFAULT 0,
  archived INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS phases (
  phase_id TEXT PRIMARY KEY,
  adw_id TEXT REFERENCES sessions,
  seq INTEGER,
  name TEXT,
  kind TEXT,
  owner TEXT,
  description TEXT,
  status TEXT DEFAULT 'fail',
  attempt INTEGER DEFAULT 0,
  retries INTEGER DEFAULT 0,
  error TEXT,
  started_at TEXT,
  ended_at TEXT
);

CREATE TABLE IF NOT EXISTS events (
  event_id TEXT PRIMARY KEY,
  adw_id TEXT REFERENCES sessions,
  phase_id TEXT REFERENCES phases,
  parent_id TEXT,
  type TEXT,
  name TEXT,
  payload_json TEXT,
  tokens INTEGER,
  started_at TEXT,
  ended_at TEXT
);

CREATE TABLE IF NOT EXISTS envelopes (
  envelope_id TEXT PRIMARY KEY,
  adw_id TEXT REFERENCES sessions,
  phase_id TEXT REFERENCES phases,
  agent TEXT,
  output_type TEXT,
  payload_json TEXT,
  valid INTEGER,
  attempt INTEGER,
  created_at TEXT
);

CREATE TABLE IF NOT EXISTS gate_results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  adw_id TEXT REFERENCES sessions,
  phase_id TEXT REFERENCES phases,
  attempt INTEGER,
  gate TEXT,
  passed INTEGER,
  violations_json TEXT,
  checks_json TEXT,
  created_at TEXT
);

CREATE TABLE IF NOT EXISTS processes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  adw_id TEXT REFERENCES sessions,
  kind TEXT,
  name TEXT,
  pid INTEGER,
  command TEXT,
  started_at TEXT,
  ended_at TEXT
);

CREATE TABLE IF NOT EXISTS agent_sessions (
  adw_id TEXT REFERENCES sessions,
  agent TEXT,
  coding_agent TEXT,
  model TEXT,
  color TEXT,
  session_id TEXT,
  context_tokens INTEGER,
  context_window INTEGER,
  created_at TEXT,
  last_used_at TEXT,
  PRIMARY KEY (adw_id, agent)
);

CREATE TABLE IF NOT EXISTS tickets (
  id TEXT PRIMARY KEY,
  provider TEXT NOT NULL,
  external_id TEXT,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'needs-triage',
  prompt_file TEXT,
  adw_id TEXT,
  source_url TEXT,
  context TEXT NOT NULL DEFAULT '',
  kind TEXT NOT NULL DEFAULT 'implementation',
  tracked INTEGER NOT NULL DEFAULT 1,
  origin TEXT NOT NULL DEFAULT 'internal',
  parent_id TEXT,
  spec TEXT NOT NULL DEFAULT '',
  rejection_feedback TEXT NOT NULL DEFAULT '',
  created_at TEXT,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS ticket_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ticket_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  actor TEXT NOT NULL DEFAULT 'system',
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ticket_runs (
  ticket_id TEXT NOT NULL,
  adw_id TEXT NOT NULL,
  created_at TEXT,
  PRIMARY KEY (ticket_id, adw_id)
);

CREATE TABLE IF NOT EXISTS ticket_mrs (
  ticket_id TEXT PRIMARY KEY,
  repo TEXT NOT NULL,
  iid TEXT NOT NULL,
  url TEXT NOT NULL DEFAULT '',
  created_at TEXT
);

CREATE TABLE IF NOT EXISTS notify_threads (
  ticket_id TEXT PRIMARY KEY,
  channel TEXT NOT NULL,
  thread_ts TEXT NOT NULL,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS notify_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ticket_id TEXT NOT NULL,
  ts TEXT NOT NULL,
  ok INTEGER NOT NULL,
  error TEXT,
  attempts INTEGER NOT NULL,
  thread_ts TEXT,
  channel TEXT
);

CREATE TABLE IF NOT EXISTS sandbox_run (
  adw_id TEXT PRIMARY KEY,
  container TEXT NOT NULL,
  container_port INTEGER,
  host_port INTEGER,
  review_url TEXT,
  review_command TEXT,
  instructions TEXT DEFAULT '',
  status TEXT,
  updated_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_ticket_events_ticket ON ticket_events (ticket_id, created_at);
